import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const editorialNew = localFont({
  src: [
    {
      path: "../public/Fonts/PPEditorialNew-Ultralight.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/Fonts/PPEditorialNew-UltralightItalic.otf",
      weight: "200",
      style: "italic",
    },
  ],
  variable: "--font-editorial-new",
});

const ppNeueYork = localFont({
  src: [
    {
      path: "../public/Fonts/PPNeueYork-CondensedLight.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/Fonts/PPNeueYork-CondensedMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/Fonts/PPNeueYork-CondensedExtrabold.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-pp-neue-york",
});

const optiAltoGreeting = localFont({
  src: [
    {
      path: "../public/Fonts/OPTIAltoGreeting Script.otf",
      style: "normal",
    },
  ],
  variable: "--font-optiAlto",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${optiAltoGreeting.variable} ${editorialNew.variable} ${ppNeueYork.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
